### ISSUE TITLE
Misc. text formatting/punctuation updates

### ISSUE THREAD

**Issue by MaryLJ** [IHE/ITI.PMIR#9]
**Section Number**  2:3.94

**Issue** See Proposed Changes

**Proposed Changes**
1.	Table 2:3.94.2-1 needs to be bold
2.	In Table 2:3.94.2-1, the last row, remove the period  for consistency
3.	In Section 2:3.94.4.1 Remove the italics from Subscription Resource in the sentence "The Subscribe to Patient Updates message is a FHIR create operation on a Subscription Resource."

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by lukeaduncan** [comment]
Merged pull request so closing.
